service: colkie

plugins:
  - serverless-iam-roles-per-function
  - serverless-esbuild
  - serverless-prune-plugin
  - serverless-reqvalidator-plugin
  - serverless-openapi-documentation
  - serverless-offline

package:
  individually: true
  exclude:
    - .serverless/**
    - .git/**

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${self:custom.stage}
  region: eu-west-2
  environment:
    stage: ${self:custom.stage}
    dbHost: "123"
    dbUserName: postgres
    dbPassword: ${self:custom.postgres.password}
    dbMaxConnections: 100
    DATABASE_URL: postgres://${self:custom.postgres.username}:${self:custom.postgres.password}@${self:custom.rdsHost}/${self:custom.postgres.dbName}

custom:
  documentation: ${file(sls/documentation/serverless.doc.yml):documentation}
  esbuild:
    target: "node16"
    concurrency: 10
    bundle: true
    minify: false
    external:
      - "@prisma"
  postgres:
    dbName: colkie
    username: production
    password: ${ssm:${self:custom.rdsSecretName}}
    maxConnections:
      production: 100
    dbInstanceClass:
      production: db.t4g.micro
    allocatedStorage:
      production: "20"
    vpcCIDR: 10
  rdsSecretName: /rds/password
  rdsHost: colkie.ctmmxcjr8kn2.eu-west-2.rds.amazonaws.com
  stage: ${opt:stage, 'production'}
  bucketName: ${self:service}-swagger-${self:custom.stage}

functions:
  - ${file(sls/functions/addUserToRoom.yml)}
  - ${file(sls/functions/createRoom.yml)}
  - ${file(sls/functions/getLatestMessages.yml)}
  - ${file(sls/functions/sendMessage.yml)}
  - ${file(sls/functions/createUser.yml)}

resources:
  # RDS
  - ${file(sls/resources/rds/database.yml)}
  - ${file(sls/resources/rds/vpc.yml)}
  # SECRETS
  - ${file(sls/resources/secrets/database.yml)}
  # # S3
  # - ${file(sls/resources/s3/bucket.yml)}
  # - ${file(sls/resources/s3/bucketPolicy.yml)}
  # API GATEWAY
  - ${file(sls/resources/apigateway/reqValidator.yml)}
  - ${file(sls/resources/apigateway/responses.yml)}
